### ISSUE TITLE
Getting errors when clipping particular page

### ISSUE THREAD

**Issue by lakdafari** [anilkumarum/mark-clipper#10]
On https://www.food.com/recipe/oven-crisp-chicken-wings-40497

Got these errors in console:

TypeError: Cannot read properties of undefined (reading 'children')
    at d.generateMarkContent (auto-clip-article.js:1:3246)
    at async auto-clip-article.js:1:3340

**Comment by lakdafari** [comment]
Seems to work ok on other sites I have tried

**Comment by anilkumarum** [comment]
Above mentioned bugs fixed in version 1.0.12

Please re-install extension.

I hope I will fixed all known bugs and If you find more bugs,please let me know

Thanks
Have a nice day
