### ISSUE TITLE
how to change clipped content. 

### ISSUE THREAD

**Issue by username-8** [anilkumarum/mark-clipper#2]
Awesome extension Lov it! 

i would like the option to have 
1. YYYY/MM/DD option for date
2. save file name as **web page title** instead of date.. or `YYY-MM-DD-{title}`
3. and add a space after `:` in YAML 

currently this is what we get 
```
created:4/9/24, 2:36 PM
tags:
source:https://www.khanacademy.org/economics-finance-domain/macroeconomics/macro-basic-economics-concepts/macro-opportunity-cost-and-the-production-possibilities-curve/v/production-possibilities-frontier
author:  
writtenAt:
domain:www.khanacademy.org
```
which shows error, so i wanna change it to 

```
created: 4/9/24, 2:36 PM
tags: 
source: https://www.khanacademy.org/economics-finance-domain/macroeconomics/macro-basic-economics-concepts/macro-opportunity-cost-and-the-production-possibilities-curve/v/production-possibilities-frontier
author:  
writtenAt: 
domain: www.khanacademy.org
```

**Comment by anilkumarum** [comment]
Sorry for late reply
Thanks for creating first issue in this repo.

1. I added `YYYY/MM/DD` option for date
2. filename format is `YYYY-MM-DD-{title}`
`const pageTitle = new Date().toISOString().slice(0, 10) + "-" + document.title.slice(0, 100)`
3. I added space after `:` in frontmatter yaml
