### ISSUE TITLE
BAGS

### ISSUE THREAD

**Issue by Andry042023** [anilkumarum/mark-clipper#5]
![image](https://github.com/anilkumarum/mark-clipper/assets/130758297/4bccfff0-ee60-4367-bffc-9eef61bceb26)

**Comment by Andry042023** [comment]
![image](https://github.com/anilkumarum/mark-clipper/assets/130758297/de520199-de4f-4a3c-86be-c6ec8cbe8d15)

**Comment by Andry042023** [comment]
![image](https://github.com/anilkumarum/mark-clipper/assets/130758297/57ab5a2d-7cf2-45f3-8b91-0d01a2cbbd3e)

**Comment by Andry042023** [comment]
![image](https://github.com/anilkumarum/mark-clipper/assets/130758297/a5c0e17c-fc0e-4677-8c25-40822d78bcd5)

**Comment by anilkumarum** [comment]
> ![image](https://private-user-images.githubusercontent.com/130758297/343201236-4bccfff0-ee60-4367-bffc-9eef61bceb26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyODI2NjgsIm5iZiI6MTcyMDI4MjM2OCwicGF0aCI6Ii8xMzA3NTgyOTcvMzQzMjAxMjM2LTRiY2NmZmYwLWVlNjAtNDM2Ny1iZmZjLTllZWY2MWJjZWIyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQxNjEyNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OWE2MGU1OTg1YmI5NTg2NWJiN2U5MDJiZWM1ZmQ5OTEwNmIwOWNmYzQ4MjE4NWNkMmFmNDljYTBhMDgwN2I1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3mXVusCvFFCGgNB4zK6RJqjFeVMXOkxyWxBW2Y2skp8)

BUG fixed.
new created note now available in right click note list, screenshot note list

**Comment by anilkumarum** [comment]
> ![image](https://private-user-images.githubusercontent.com/130758297/343201376-de520199-de4f-4a3c-86be-c6ec8cbe8d15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyODI2NjgsIm5iZiI6MTcyMDI4MjM2OCwicGF0aCI6Ii8xMzA3NTgyOTcvMzQzMjAxMzc2LWRlNTIwMTk5LWRlNGYtNGEzYy04NmJlLWM2ZWM4Y2JlOGQxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQxNjEyNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWRlOTMzNTQ0MWJkYzRhMzJlMDc3NjZjZGY4MWU5ZmQ1YjU5ODgxNmZhNDZmMGYxOGFlODkxODFkMWVmMzJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HH8JW9dO54Ut-dWi4tw0btBN9mhgntciyfVJdopbmWg)

ADDED: Small cancel button added in version 1.0.2

**Comment by anilkumarum** [comment]
> ![image](https://private-user-images.githubusercontent.com/130758297/343201428-57ab5a2d-7cf2-45f3-8b91-0d01a2cbbd3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyODI2NjgsIm5iZiI6MTcyMDI4MjM2OCwicGF0aCI6Ii8xMzA3NTgyOTcvMzQzMjAxNDI4LTU3YWI1YTJkLTdjZjItNDVmMy04YjkxLTBkMDFhMmNiYmQzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQxNjEyNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjlhYmI3YWQ3MTllOTgyYTc3OTFlNTY2YmQ2NmM1ZjgxY2FmOGQxOTVjNWE3OGY0ZTg2NTZmODBmNzlkNmE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TE3JT87_t85rwtUfT8rmxw5Xwx7ucNd7QGUXxKzytjw)

FIXED: markclipper now add relative path `../../images/` instead of `/images`.

**Comment by anilkumarum** [comment]
> ![image](https://private-user-images.githubusercontent.com/130758297/343201488-a5c0e17c-fc0e-4677-8c25-40822d78bcd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyODI2NjgsIm5iZiI6MTcyMDI4MjM2OCwicGF0aCI6Ii8xMzA3NTgyOTcvMzQzMjAxNDg4LWE1YzBlMTdjLWZjMGUtNDY3Ny04YzI1LTQwODIyZDc4YmNkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQxNjEyNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzY1YzA2YzQ1YjMzOWE5ODE3MzExZmEyOGMxNzcwZWJkOWZlZmVkNjIzNDNjZmYyYjc4NTRiZTM5Y2U5ZWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xx7DvcJrrMWU4Yg3XhFVcyVj-kyFjicJsrFvzBgz-zQ)

Sorry, i don't understand properly.
markclipper use native browser `<select>` element to display dropdown note  list.
native browser `<select>` provide basic search feature. Just open dropdown list then press character key on keyboard to search note in dropdown list.
I added create new note option.
Please elaborate this issue
