### ISSUE TITLE
cant use clip aritcle

### ISSUE THREAD

**Issue by fulln** [anilkumarum/mark-clipper#6]
when i clip the article , console report error
![image](https://github.com/anilkumarum/mark-clipper/assets/24662311/b48dafb6-4ac0-4109-b0c1-9bf5e914ccb2)

**Comment by anilkumarum** [comment]
This error throw due to svg element.
Bug fixed in version 1.0.2 on 7 July.
If you find more bugs, please let me know. 
I will fixed bugs ASAP
Thanks
Have a nice day
